theme: jekyll-theme-leap-day
title: aki's left brain - blog archives
description: AKIHIKO SHIRAI, Ph.D (Engineering) is working for research and development for VR live entertainment. 
show_downloads: false
google_analytics: UA-168023643-1
